kind: Secret
apiVersion: v1
metadata:
  name: github-builds-secret
  namespace: github-builds
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
  .git-credentials: |
    https://martinmlouis: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@github.com
