kind: Secret
apiVersion: v1
metadata:
  name: github-builds-secret
  namespace: github-builds
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
  .git-credentials: |
    https://martinmlouis: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@github.com
