apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github-builds-dev-branch-pipeline
  namespace: github-builds
spec:
  description: | 
    This pipeline clones a git repo.
    1. builds the helm chart for dev branch for each version and pushes to helm repo
    2. deploys the argocd application for each version
  params:
  - name: repo-url
    type: string
    description: The git repo URL to clone from.
  - name: branch
    type: string
    description: The git repo BRANCH to clone from.
  workspaces:
  - name: shared-data
    description: | 
      This workspace contains the cloned repo files, so they can be read by the
      next task.
  - name: git-credentials
    description: My basic-auth credentials
  - name: harbor-access-secret
    description: Credentials to use to pull/push for harbor registry.

  tasks:
  - name: fetch-github-repo
    taskRef:
      resolver: git
      params:
        - name: url
          value: https://github.com/martinmlouis/github_builds.git
        - name: pathInRepo
          value: demo/tekton-resources/git-clone.yaml        
    params:
    - name: url
      value: $(params.repo-url)            
    - name: branch
      value: "dev"
    workspaces:
    - name: output
      workspace: shared-data
    - name: basic-auth
      workspace: git-credentials
#  - name: import-resources
#    runAfter: ["fetch-github-repo"]
#    taskRef:
#      name: import-resources
#    workspaces:
#    - name: shared-data
#      workspace: shared-data
#    params:
#    - name: path 
#      value: "demo/tekton-resources"
  - name: deploy-argocd-apps-task
    taskRef:
      resolver: git
      params:
        - name: url
          value: https://github.com/martinmlouis/github_builds.git
        - name: pathInRepo
          value: demo/tekton-resources/deploy_argocd_apps_task.yaml
    params:
    - name: url
      value: $(params.repo-url)            
    - name: branch
      value: "dev"
    - name: NAME
      value: "eCHIMP-v0.1.0"
    - name: REPO
      value: https://github.com/martinmlouis/nginx.git
    - name: PATH
      value: "v0.1.0"
    - name: NAMESPACE
      value: "github_builds"
    - name: DESTINATION_SERVER
      value: "https://kubernetes.default.svc"
    - name: LABEL
      value: "Version=v0.1.0"
    - name: ARGOCD_SERVER
      value: "argocd.35.212.92.161.nip.io"
    - name: VALUES_FILE
      value: "values.yaml"
    workspaces:
    - name: harbor-access-secret
      workspace: harbor-access-secret
    - name: git-credentials
      workspace: git-credentials
