apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: github-builds-dev-branch-trigger
  namespace: github-builds
spec:
  interceptors:
    - ref: 
        name: "cel"
      params:
      - name: "filter"
        value: "body.ref.contains('dev') && body.repository.name == 'github_builds'"
      - name: "overlays"
        value:
          - key: branch
            expression: "body.ref.split('/')[2]"
          - key: repo-url
            expression: "body.repository.url"
  bindings:
  - ref: github-builds-dev-branch-triggerbinding
  template:
    ref: github-builds-dev-branch-triggertemplate

