apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-builds-dev-branch-triggerbinding
  namespce: github-builds
spec:
  params:
    - name: branch
      value: "$(extensions.branch)"
    - name: repo-url
      value: "$(extensions.repo-url)"
