apiVersion: tekton.dev/v1 # or tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push-argocd-apps-helm-task
spec:
  workspaces:
    - name: harbor-access-secret
    - name: shared-data
    - name: git-credentials
  steps:
    - name: read
      image: harbor.35.212.92.161.nip.io/leidos/helm:3.16.1
      script: |
        #!/usr/bin/env bash
        pwd
        ls -ltr $(workspaces.shared-data.path)
        cd $(workspaces.shared-data.path)
        ls |grep v > versions_to_build_helm_charts.txt
        versions_to_build_helm_charts_filename="versions_to_build_helm_charts.txt"

        while read version
        do
          echo $version
        done < "${versions_to_build_helm_charts_filename}"

