apiVersion: tekton.dev/v1 # or tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push-argocd-apps-helm-task
spec:
  workspaces:
    - name: harbor-access-secret
    - name: shared-data
    - name: git-credentials
  steps:
    - name: read
      image: harbor.35.212.92.161.nip.io/leidos/helm:3.16.1
      script: |
        #!/usr/bin/env bash
        
        set -x
        #pwd
        ls -ltr $(workspaces.shared-data.path)
        cd $(workspaces.shared-data.path)/charts
        ls |grep [0-9] > versions_to_build_helm_charts.txt
        versions_to_build_helm_charts_filename="versions_to_build_helm_charts.txt"
        while read version
        do
          echo $version
          helm lint ${version}
          helm template ${version}
          helm package ${version}
          chart_version=$(echo ${version} |cut -d"v" -f2)
          echo ${chart_version}
          chart_name=$(grep ^name: ${version}/Chart.yaml |cut -d" " -f2)
          curl -k -XDELETE   http:/chartmuseum.35.212.92.161.nip.io/api/charts/${chart_name}/${chart_version}
          curl -k  --data-binary "@${chart_name}-${chart_version}.tgz" http:/chartmuseum.35.212.92.161.nip.io/api/charts
          sleep 30
          cp ${version}/dev-values.yaml ${version}/values.yaml
          curl -k -XDELETE   http:/chartmuseum-dev.35.212.92.161.nip.io/api/charts/${chart_name}/${chart_version}
          curl -k  --data-binary "@${chart_name}-${chart_version}.tgz" http:/chartmuseum-dev.35.212.92.161.nip.io/api/charts
          sleep 30
          cp ${version}/test-values.yaml ${version}/values.yaml
          curl -k -XDELETE   http:/chartmuseum-test.35.212.92.161.nip.io/api/charts/${chart_name}/${chart_version}
          curl -k  --data-binary "@${chart_name}-${chart_version}.tgz" http:/chartmuseum-test.35.212.92.161.nip.io/api/charts
          sleep 30
          cp ${version}/impl-values.yaml ${version}/values.yaml
          curl -k -XDELETE   http:/chartmuseum-impl.35.212.92.161.nip.io/api/charts/${chart_name}/${chart_version}
          curl -k  --data-binary "@${chart_name}-${chart_version}.tgz" http:/chartmuseum-impl.35.212.92.161.nip.io/api/charts
          sleep 30
          cp ${version}/prod-values.yaml ${version}/values.yaml
          curl -k -XDELETE   http:/chartmuseum-prod.35.212.92.161.nip.io/api/charts/${chart_name}/${chart_version}
          curl -k  --data-binary "@${chart_name}-${chart_version}.tgz" http:/chartmuseum-prod.35.212.92.161.nip.io/api/charts
        done < "${versions_to_build_helm_charts_filename}"

